version: '3.2'
services:
  glassfish:
    build: ./glassfish
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
    dns: ntpd # Might get ignored, using alias for backup
    dns_search: docker.ahf
    command: admin pass
    hostname: glassfish
    domainname: docker.ahf
    depends_on:
      - ntpd
    volumes:
      - ./tls:/out
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
  ntpd:
    build: ./ntpd
    dns: localhost # Might get ignored, using alias for backup
    dns_search: docker.ahf
    ports:
      - "53:53/udp"
      - "53"
      - "123/udp"
      - "31935"
      - "31935/udp"
    networks:
      default:
        aliases: # Used for when dns is ignored
          - 127.0.0.11
    hostname: dns
    domainname: docker.ahf
    volumes:
      - ./tsig:/out
      - type: volume
        source: tsig
        target: /tsig
  simpleservicediscovery:
    build: ./simpleservicediscovery
    ports:
      - "5683:5683"
      - "8045:8045"
    dns: ntpd
    dns_search: docker.ahf
    hostname: simpleservicediscovery
    domainname: docker.ahf
    depends_on:
      - ntpd
    volumes:
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
volumes:
  tsig:
  tls:
