version: '3.2'
services:
  glassfish:
    build: ./glassfish
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
    dns:
      - ntpd
    command: admin pass
    hostname: glassfish
    domainname: docker.ahf
    depends_on:
      - ntpd
    volumes:
      - ./tls:/out
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - glassfish.docker.ahf
  ntpd:
    build: ./ntpd
    dns:
      - ntpd
    ports:
      - "53:53/udp"
      - "53"
      - "123/udp"
      - "31935"
      - "31935/udp"
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - ntpd.docker.ahf
          - named.docker.ahf
          - ns.docker.ahf
    hostname: dns
    domainname: docker.ahf
    volumes:
      - ./tsig:/out
      - type: volume
        source: tsig
        target: /tsig
  simpleservicediscovery:
    build: ./simpleservicediscovery
    ports:
      - "5683:5683"
      - "8045:8045"
    dns:
      - ntpd
    hostname: simpleservicediscovery
    domainname: docker.ahf
    depends_on:
      - ntpd
    volumes:
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - simpleservicediscovery.docker.ahf
          - sdd.docker.ahf
volumes:
  tsig:
  tls:
networks:
  ahf: