version: '3.3'
services:
  glassfish:
    build: ./glassfish
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
    dns:
      - bind
    environment:
      - LOCK_OUT_DIR=false
      - GLASSFISH_ADMIN=admin
      - GLASSFISH_PASSWORD=password
      - KEYSTORE_PASSWORD=changeit
      - TESTER_KEYSTORE_PASSWORD=changeit
      - DNS_SERVER=bind
      - REGISTER_WITH_DNS=true
      - SECURE_GLASSFISH=true
      - SERVER_HOSTNAME=glassfish.docker.ahf
      - SERVER_DOMAIN=docker.ahf
      - DO_DYNAMIC_DNS_UPDATE=true
    hostname: glassfish
    domainname: docker.ahf
    depends_on:
      - bind
    volumes:
      - type: volume
        source: glassfish-domains
        target: /glassfish3/glassfish/domains/
      - type: volume
        source: glassfish-databases
        target: /glassfish3/glassfish/databases/
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - glassfish.docker.ahf
  bind:
    build: ./bind
    dns:
      - bind
    environment:
      - LOCK_OUT_DIR=false
      - ALLOW_DOMAIN_UPDATE=true
      - SERVER_DOMAIN=docker.ahf
      - SERVER_HOSTNAME=bind.docker.ahf
    ports:
      - "53:53/udp"
      - "53:53"
      - "123/udp"
      - "31935"
      - "31935/udp"
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - bind.docker.ahf
          - named.docker.ahf
          - ns.docker.ahf
    hostname: dns
    domainname: docker.ahf
    volumes:
      - type: volume
        source: tsig
        target: /tsig
  simpleservicediscovery:
    build: ./simpleservicediscovery
    ports:
      - "5683:5683"
      - "8045:8045"
    dns:
      - bind
    environment:
      - DNS_SERVER=bind
      - BROWSING_DOMAIN=docker.ahf
      - ORCHESTRATION_URL=https://glassfish.docker.ahf:8181/orchestration/store
      - AUTHORISATION_URL=https://glassfish.docker.ahf:8181/authorisation
      - WAIT_FOR_TLS_READY=true
      - WAIT_FOR_ORCH_STORE=true
      - REGISTER_WITH_DNS=true
      - DO_DYNAMIC_DNS_UPDATE=true
      - SERVER_HOSTNAME=simpleservicediscovery.docker.ahf
      - SERVER_DOMAIN=docker.ahf
    hostname: simpleservicediscovery
    domainname: docker.ahf
    depends_on:
      - bind
    volumes:
      - type: volume
        source: tsig
        target: /tsig
      - type: volume
        source: tls
        target: /tls
    networks:
      ahf:
        aliases: # Used for when dns is ignored
          - simpleservicediscovery.docker.ahf
          - sdd.docker.ahf
volumes:
  glassfish-domains:
  glassfish-databases:
  tsig:
  tls:
networks:
  ahf:

