### Set-up (add authorisation rule and publish service)
# curl -X POST http://127.0.0.1:8888/setup
POST http://127.0.0.1:8888/setup

### Set-down (remove authorisation rule and unpublish service)
# curl -X POST http://127.0.0.1:8888/setdown
POST http://127.0.0.1:8888/setdown

### Request a 'hello'
# curl -X POST http://127.0.0.1:8888/hello
POST http://127.0.0.1:8888/hello

### Stop the server remotely
# curl -X POST http://127.0.0.1:8888/stop
POST http://127.0.0.1:8888/stop
